[package]
authors = ["Juliette Cordor <me@cordor.dev>"]
description = "Stupid Fast Scoop Utils"
edition = "2024"
license = "MIT OR Apache-2.0"
name = "sfsu"
publish = true
repository = "https://github.com/winpax/sfsu"
version = "1.17.3"

[[bench]]
harness = false
name = "searching"

[[bench]]
harness = false
name = "ref-matching"

[[bench]]
harness = false
name = "serde"

[[bench]]
harness = false
name = "autoupdate"

[[bench]]
harness = false
name = "url_parsing"

[profile.release]
codegen-units = 1
lto = true

[profile.profiling]
debug = true
inherits = "release"
strip = "none"

[features]
beta = ["sprinkles-rs/beta"]
contexts = []
default = ["download", "contexts"]
download = ["sprinkles-rs/manifest-hashes"]
# Changes that fundamentally change the API are locked behind this feature flag
v2 = []

[dependencies]
anyhow = "1.0"
bat = { version = "0.26", default-features = false, features = ["regex-onig"] }
cfg-if = "1.0"
chrono = { version = "0.4", features = [
    "clock",
    "serde",
    "std",
], default-features = false }
clap = { version = "4.5", features = [
    "derive",
    "env",
    "string",
    "unicode",
    "wrap_help",
] }
console = { version = "0.16", features = ["windows-console-colors"] }
crossterm = "0.29"
derive_more = { version = "2.0", features = ["deref_mut", "deref", "as_ref"] }
dialoguer = "0.12"
futures = "0.3"
glob = "0.3.3"
hashbrown = "0.16"
heck = "0.5"
human-panic = "2.0"
indexmap = { version = "2.13", features = ["rayon"] }
itertools = "0.14"
konst = "0.4"
log = { version = "0.4", features = ["std"] }
open = "5.1"
parking_lot = "0.12"
prodash = { version = "31", features = [
    "render-line",
    "render-line-crossterm",
] }
quork = { version = "0.9", default-features = false, features = ["root"] }
rand = "0.9"
ratatui = { version = "0.30", features = ["macros"] }
rayon = "1.10"
regex = "1.12"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
shadow-rs = "1.2"
sprinkles-rs = { version = "0.23", features = ["clap"] }
thiserror = "2.0"
tokio = { version = "1.47", features = ["full"] }
vt3 = "0.7"
which = "8.0"
windows = { version = "0.62", features = ["Win32_Storage_FileSystem"] }
windows-version = "0.1"
winreg = "0.55"

[dev-dependencies]
criterion = { version = "0.8", features = ["async_tokio", "html_reports"] }
url = "2.5.4"

[build-dependencies]
contribs = { git = "https://github.com/winpax/contribs.git", version = "0.1" }
dotenv = "0.15"
git2 = "0.20"
shadow-rs = "1.0"
tokio = { version = "1.37", features = ["full"] }
toml_edit = "0.23"
winres = "0.1"
