#!/usr/bin/env python
#MISE description="Hash a file with SHA256"
#USAGE arg "<file>" help="The file to hash"

import hashlib
import os

# Totally arbitrary
BUF_SIZE = 65536  # 64 kb
TO_HASH = os.environ["usage_file"]

hasher = hashlib.sha256()

with open(TO_HASH, "rb") as f:
    while True:
        data = f.read(BUF_SIZE)
        if not data:
            break

        hasher.update(data)


with open(TO_HASH + ".sha256", "w", encoding="utf8") as f:
    f.write(hasher.hexdigest())
